apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: visits
  namespace: dev
spec:
  hosts:
  - visits-service
  - visits-service.dev.svc.cluster.local
  http:
  - route:
    - destination:
        host: visits-service
        port:
          number: 8082
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,gateway-error,connect-failure,refused-stream"
    timeout: 10s